version: "3.9"

services:
  postgres:
    container_name: trello
    image: postgres:11.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trello
    ports:
      - "5432:5432"