server:
  port: 8081

spring:
  application:
    name: spotify-service
  datasource:
    url: jdbc:postgresql://localhost:5432/trello
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true